from __future__ import annotations

import math
from pathlib import Path

import streamlit as st
import streamlit.components.v1 as components

import escapist_engine_unique_colors_v10 as engine


MOMENT_GAP = 0.45


def radius_tail_for_largest_finite_integer_moment(
    growth: float,
    moment_order: int,
) -> float:
    """Choose q so integer moments through m are finite, but m+1 is not.

    For P(K=k)=(1-q)q^k and R=R_0 a^K, E[R^s] is finite exactly
    when q a^s < 1.  Taking q=a^{-(m+MOMENT_GAP)}, with 0<MOMENT_GAP<1,
    puts the critical exponent strictly between m and m+1.
    """

    return growth ** (-(moment_order + MOMENT_GAP))


def parse_seed(seed_text: str) -> int | None:
    stripped = seed_text.strip()
    if not stripped:
        return None
    return int(stripped)


def download_button(path: str, label: str, key: str) -> None:
    file_path = Path(path)
    if not file_path.exists():
        return
    with file_path.open("rb") as file_handle:
        st.download_button(
            label=label,
            data=file_handle.read(),
            file_name=file_path.name,
            key=key,
        )


st.set_page_config(
    page_title="Escapist in a dynamic Brownian environment",
    page_icon="🏃",
    layout="wide",
)

st.title("Escapist in a dynamic Brownian environment")
st.caption(
    "Two spatial dimensions are shown horizontally and time is the vertical "
    "coordinate. The complete random environment is generated first; only "
    "afterwards does the fugitive extract a complete recursively branching "
    "subtree from one admissible predecessor tree."
)

with st.sidebar:
    st.header("Simulation controls")

    fugitive_speed = st.slider(
        "Fugitive speed",
        min_value=1.0,
        max_value=8.0,
        value=4.5,
        step=0.1,
        help="Maximum spatial distance travelled per unit of time.",
    )
    particle_density = st.slider(
        "Particle density λ",
        min_value=0.005,
        max_value=0.150,
        value=0.080,
        step=0.005,
        format="%.3f",
        help="Intensity of the initial Poisson point process.",
    )
    moment_order = st.select_slider(
        "Largest finite integer radius moment",
        options=list(range(2, 9)),
        value=2,
        help=(
            "For the selected m, the radius law has finite moments through "
            "E[R^m], while E[R^(m+1)] diverges. The minimum is 2 because the "
            "spatial dimension is two."
        ),
    )
    start_region_radius = st.slider(
        "Random-start region radius",
        min_value=0.8,
        max_value=4.0,
        value=3.0,
        step=0.1,
        help=(
            "After the complete environment is generated, the initial point "
            "is sampled uniformly among vacant grid points in this disk."
        ),
    )
    branching_factor = st.select_slider(
        "Descendants generated by every branch",
        options=[4, 5],
        value=5,
        help=(
            "At every coarse time box, each retained branch must have this "
            "many distinct admissible descendants."
        ),
    )
    branching_generations = st.slider(
        "Branching generations",
        min_value=2,
        max_value=3,
        value=2,
        step=1,
        help=(
            "The number of terminal paths is factor^generations: for example, "
            "5^3 = 125."
        ),
    )

    with st.expander("Advanced radius settings"):
        radius_base = st.slider(
            "Base radius R₀",
            min_value=0.10,
            max_value=0.80,
            value=0.40,
            step=0.05,
        )

    with st.expander("Space-time tessellation"):
        tessellation_spatial_divisions = st.slider(
            "Spatial divisions per axis",
            min_value=3,
            max_value=6,
            value=4,
            step=1,
            help="Fewer divisions produce larger displayed boxes.",
        )
        st.caption(
            "The number of time boxes equals the number of branching "
            "generations selected above."
        )
        radius_growth = st.slider(
            "Level growth a",
            min_value=1.05,
            max_value=1.80,
            value=1.50,
            step=0.05,
        )

    radius_tail = radius_tail_for_largest_finite_integer_moment(
        radius_growth,
        moment_order,
    )
    critical_exponent = -math.log(radius_tail) / math.log(radius_growth)
    requested_moment = (
        radius_base**moment_order
        * (1.0 - radius_tail)
        / (1.0 - radius_tail * radius_growth**moment_order)
    )

    st.markdown(
        rf"""
        **Radius law selected**

        $P(K=k)=(1-q)q^k$, $R_k=R_0a^k$

        $q={radius_tail:.4f}$, critical exponent $={critical_exponent:.2f}$

        $\mathbb{{E}}[R^{moment_order}]={requested_moment:.4f}$
        """
    )

    generate_video = st.checkbox(
        "Generate MP4 video",
        value=False,
        help="The video takes considerably longer than the PNG and HTML.",
    )
    seed_text = st.text_input(
        "Seed (optional)",
        value="",
        placeholder="Blank = a new environment",
    )
    run_button = st.button(
        "Generate simulation",
        type="primary",
        width="stretch",
    )


if run_button:
    try:
        selected_seed = parse_seed(seed_text)
    except ValueError:
        st.error("The seed must be an integer or left blank.")
    else:
        engine.SEED = selected_seed
        engine.MAX_TARGET_SPEED = float(fugitive_speed)
        engine.POISSON_INTENSITY = float(particle_density)
        engine.RADIUS_BASE = float(radius_base)
        engine.RADIUS_LEVEL_GROWTH = float(radius_growth)
        engine.RADIUS_LEVEL_TAIL = float(radius_tail)
        engine.RADIUS_MOMENT_ORDER = float(moment_order)
        engine.ENTRANCE_RADIUS = float(start_region_radius)
        engine.BRANCHING_FACTOR = int(branching_factor)
        engine.TESSELLATION_SPATIAL_DIVISIONS = int(
            tessellation_spatial_divisions
        )
        engine.TESSELLATION_TIME_DIVISIONS = int(branching_generations)
        engine.SAVE_VIDEO = bool(generate_video)
        engine.OPEN_INTERACTIVE_HTML = False

        try:
            with st.spinner(
                "Generating the complete environment and then finding the "
                "branching escape tree..."
            ):
                result = engine.main()
        except Exception as error:
            st.session_state.pop("escapist_result", None)
            st.error(f"Simulation failed: {error}")
            st.info(
                "The fixed environment was not silently replaced. If it has "
                "no admissible path, run again for a new independent one or "
                "change the controls."
            )
        else:
            st.session_state["escapist_result"] = result
            st.success("Simulation completed.")


result = st.session_state.get("escapist_result")

if result is None:
    st.info(
        "Choose the parameters in the left panel and press "
        "“Generate simulation”."
    )
else:
    metric_columns = st.columns(5)
    metric_columns[0].metric("Particles", result["particle_count"])
    metric_columns[1].metric(
        "Maximum speed",
        f'{result["maximum_speed"]:.3f}',
    )
    metric_columns[2].metric(
        "Minimum clearance",
        f'{result["minimum_clearance"]:.3f}',
    )
    metric_columns[3].metric(
        "Speed budget used",
        f'{100.0 * result["speed_budget_fraction"]:.1f}%',
    )
    metric_columns[4].metric("Terminal paths", result["branch_count"])
    st.caption(
        "Random initial point selected after the environment: "
        f'({result["start_point"][0]:.3f}, '
        f'{result["start_point"][1]:.3f})'
    )
    color_chips = " ".join(
        f'<span title="{color}" style="display:inline-block;width:1.1rem;'
        f'height:1.1rem;border-radius:50%;background:{color};border:1px '
        f'solid #ffffff;vertical-align:middle"></span>'
        for color in result["escape_colors"]
    )
    st.markdown(
        f"One color for each terminal path: {color_chips}",
        unsafe_allow_html=True,
    )

    tab_names = [
        "Website image",
        "Scientific image",
        "Interactive 3D",
        "Branch validation",
        "Radius realization",
    ]
    if result.get("video_path"):
        tab_names.append("Video")
    tabs = st.tabs(tab_names)

    with tabs[0]:
        st.image(result["website_image_path"], width="stretch")
        download_button(
            result["website_image_path"],
            "Download website PNG",
            "download_website_png",
        )

    with tabs[1]:
        st.image(result["image_path"], width="stretch")
        download_button(
            result["image_path"],
            "Download PNG",
            "download_png",
        )

    with tabs[2]:
        interactive_path = Path(result["interactive_path"])
        components.html(
            interactive_path.read_text(encoding="utf-8"),
            height=820,
            scrolling=True,
        )
        download_button(
            result["interactive_path"],
            "Download interactive HTML",
            "download_html",
        )

    with tabs[3]:
        st.write(
            f'A regular {result["branching_factor"]}-ary tree with '
            f'{result["branching_generations"]} generations produced '
            f'{result["branch_count"]} validated root-to-exit paths.'
        )
        st.dataframe(
            result["branch_statistics"],
            width="stretch",
            hide_index=True,
        )

    with tabs[4]:
        st.write(
            f'Run seed: `{result["run_seed"]}`  '
            f'— theoretical E[R^{result["radius_moment_order"]:g}] = '
            f'`{result["expected_requested_moment"]:.6f}`'
        )
        st.dataframe(
            result["radius_levels"],
            width="stretch",
            hide_index=True,
        )

    if result.get("video_path"):
        with tabs[5]:
            st.video(result["video_path"])
            download_button(
                result["video_path"],
                "Download MP4",
                "download_mp4",
            )